# Translations template for oslo.vmware.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the oslo.vmware
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: oslo.vmware 0.5.0.11.gd9ada2a\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-25 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: oslo/vmware/api.py:313
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""

#: oslo/vmware/api.py:417
#, python-format
msgid "Task: %(task)s failed with error: %(error)s."
msgstr ""

#: oslo/vmware/api.py:471
#, python-format
msgid "Lease: %(lease)s is in error state. Details: %(error_msg)s."
msgstr ""

#: oslo/vmware/api.py:478
#, python-format
msgid "Unknown state: %(state)s for lease: %(lease)s."
msgstr ""

#: oslo/vmware/exceptions.py:48
msgid "exception_summary must not be a list"
msgstr ""

#: oslo/vmware/exceptions.py:81
msgid "fault_list must be a list"
msgstr ""

#: oslo/vmware/exceptions.py:83
msgid "details must be a dict"
msgstr ""

#: oslo/vmware/exceptions.py:116
msgid "An unknown exception occurred."
msgstr ""

#: oslo/vmware/exceptions.py:141
msgid "VMware Driver configuration fault."
msgstr ""

#: oslo/vmware/exceptions.py:145
msgid "No default value for use_linked_clone found."
msgstr ""

#: oslo/vmware/exceptions.py:149
#, python-format
msgid "Missing parameter : %(param)s"
msgstr ""

#: oslo/vmware/exceptions.py:153
msgid "Resource already exists."
msgstr ""

#: oslo/vmware/exceptions.py:158
msgid "Cannot delete file."
msgstr ""

#: oslo/vmware/exceptions.py:163
msgid "File already exists."
msgstr ""

#: oslo/vmware/exceptions.py:168
msgid "File fault."
msgstr ""

#: oslo/vmware/exceptions.py:173
msgid "File locked."
msgstr ""

#: oslo/vmware/exceptions.py:178
msgid "File not found."
msgstr ""

#: oslo/vmware/exceptions.py:183
msgid "Invalid power state."
msgstr ""

#: oslo/vmware/exceptions.py:188
msgid "Invalid property."
msgstr ""

#: oslo/vmware/exceptions.py:193
msgid "No Permission."
msgstr ""

#: oslo/vmware/exceptions.py:198
msgid "Not Authenticated."
msgstr ""

#: oslo/vmware/image_transfer.py:170
#, python-format
msgid "Image: %s is in killed state."
msgstr ""

#: oslo/vmware/image_transfer.py:184
#, python-format
msgid "Image: %(image)s is in unknown state: %(state)s."
msgstr ""

#: oslo/vmware/image_transfer.py:193
#, python-format
msgid "Error occurred while writing image: %s"
msgstr ""

#: oslo/vmware/image_transfer.py:278
msgid "Error occurred during file read-write task."
msgstr ""

#: oslo/vmware/image_transfer.py:365
msgid "No image destination given."
msgstr ""

#: oslo/vmware/image_transfer.py:382
#, python-format
msgid ""
"Error occurred during image transfer with reader: %(reader)s and writer: "
"%(writer)s"
msgstr ""

#: oslo/vmware/rw_handles.py:143
msgid "Could not retrieve VMDK URL from lease info."
msgstr ""

#: oslo/vmware/rw_handles.py:193 oslo/vmware/rw_handles.py:336
#, python-format
msgid "Invalid scheme: %s."
msgstr ""

#: oslo/vmware/rw_handles.py:207
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to file with URL ="
" %s."
msgstr ""

#: oslo/vmware/rw_handles.py:222 oslo/vmware/rw_handles.py:376
#, python-format
msgid "Connection error occurred while writing data to %s."
msgstr ""

#: oslo/vmware/rw_handles.py:230 oslo/vmware/rw_handles.py:384
#, python-format
msgid "Error occurred while writing data to %s."
msgstr ""

#: oslo/vmware/rw_handles.py:355
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to VMDK file with "
"URL = %s."
msgstr ""

#: oslo/vmware/rw_handles.py:521
#, python-format
msgid "Error occurred while opening URL: %s for reading."
msgstr ""

#: oslo/vmware/rw_handles.py:547
#, python-format
msgid "Error occurred while reading data from %s."
msgstr ""

#: oslo/vmware/service.py:132
msgid "Error occurred while calling RetrievePropertiesEx."
msgstr ""

#: oslo/vmware/service.py:210
#, python-format
msgid "No such SOAP method %s."
msgstr ""

#: oslo/vmware/service.py:216
#, python-format
msgid "httplib error in %s."
msgstr ""

#: oslo/vmware/service.py:220
#, python-format
msgid "urllib2 error in %s."
msgstr ""

#: oslo/vmware/service.py:231
#, python-format
msgid "Socket error in %s."
msgstr ""

#: oslo/vmware/service.py:236
#, python-format
msgid "Type error in %s."
msgstr ""

#: oslo/vmware/service.py:239
#, python-format
msgid "Exception in %s."
msgstr ""

#: oslo/vmware/objects/datastore.py:34
msgid "Datastore name cannot be None"
msgstr ""

#: oslo/vmware/objects/datastore.py:36
msgid "Datastore reference cannot be None"
msgstr ""

#: oslo/vmware/objects/datastore.py:38
msgid "Invalid capacity"
msgstr ""

#: oslo/vmware/objects/datastore.py:41
msgid "Capacity is smaller than free space"
msgstr ""

#: oslo/vmware/objects/datastore.py:146
msgid "Datastore name cannot be empty"
msgstr ""

#: oslo/vmware/objects/datastore.py:151 oslo/vmware/objects/datastore.py:192
msgid "Path component cannot be None"
msgstr ""

#: oslo/vmware/objects/datastore.py:205
msgid "Datastore path cannot be empty"
msgstr ""

#: oslo/vmware/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: oslo/vmware/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

